object frmMain: TfrmMain
  Left = 0
  Top = 0
  Caption = 'CWStudio Component Library'
  ClientHeight = 670
  ClientWidth = 1096
  Color = clBtnFace
  CustomTitleBar.Control = brTitle
  CustomTitleBar.Enabled = True
  CustomTitleBar.Height = 31
  CustomTitleBar.SystemColors = False
  CustomTitleBar.SystemButtons = False
  CustomTitleBar.BackgroundColor = 13924352
  CustomTitleBar.ForegroundColor = clWhite
  CustomTitleBar.InactiveBackgroundColor = clWhite
  CustomTitleBar.InactiveForegroundColor = 10066329
  CustomTitleBar.ButtonForegroundColor = clWhite
  CustomTitleBar.ButtonBackgroundColor = 13924352
  CustomTitleBar.ButtonHoverForegroundColor = clWhite
  CustomTitleBar.ButtonHoverBackgroundColor = 11166464
  CustomTitleBar.ButtonPressedForegroundColor = clWhite
  CustomTitleBar.ButtonPressedBackgroundColor = 7028224
  CustomTitleBar.ButtonInactiveForegroundColor = 10066329
  CustomTitleBar.ButtonInactiveBackgroundColor = clWhite
  Constraints.MinWidth = 1100
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  GlassFrame.Enabled = True
  GlassFrame.Top = 31
  Position = poDesigned
  StyleElements = [seFont, seClient]
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  TextHeight = 15
  object brTitle: TTitleBarPanel
    Left = 0
    Top = 0
    Width = 1096
    Height = 30
    CustomButtons = <>
  end
  object pnlMenu: TPanel
    Left = 0
    Top = 30
    Width = 78
    Height = 640
    Align = alLeft
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    TabOrder = 1
    object shpLineMenu: TShape
      Left = 0
      Top = 576
      Width = 78
      Height = 1
      Align = alBottom
      ExplicitTop = 453
    end
    object pnlMenuTitle: TPanel
      Left = 0
      Top = 0
      Width = 78
      Height = 48
      Align = alTop
      BevelOuter = bvNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
    end
    object scrbMenu: TCWSScrollBox
      Left = 0
      Top = 48
      Width = 78
      Height = 528
      ShowBorder = False
      ScrollStyle = cssVertical
      Align = alClient
      TabOrder = 1
      object CWSStoreButton1: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #59407
        IconGlyphPressed = #60042
        DescriptionText = 'Home'
        Pressed = True
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton1Click
      end
      object CWSStoreButton6: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 66
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #59698
        IconGlyphPressed = #59698
        DescriptionText = 'Edits'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton6Click
      end
      object CWSStoreButton2: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 129
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #59387
        IconGlyphPressed = #59387
        DescriptionText = 'Panels'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton2Click
      end
      object CWSStoreButton5: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 192
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #59226
        IconGlyphPressed = #59226
        DescriptionText = 'Forms'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton5Click
      end
      object CWSStoreButton3: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 255
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #59231
        IconGlyphPressed = #59231
        DescriptionText = 'Buttons'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton3Click
      end
      object CWSStoreButton4: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 318
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #61802
        IconGlyphPressed = #61802
        DescriptionText = 'Progress Bars'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton4Click
      end
      object CWSStoreButton7: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 381
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #59576
        IconGlyphPressed = #59576
        DescriptionText = 'Scroll Boxes'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        OnClick = CWSStoreButton7Click
      end
      object CWSStoreButton9: TCWSStoreButton
        AlignWithMargins = True
        Left = 3
        Top = 444
        Width = 72
        Height = 57
        Align = alTop
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -9
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentFont = False
        IconFontName = 'Segoe MDL2 Assets'
        BckNormalColor = clBtnFace
        BckHoverColor = clSilver
        BckPressedColor = clWhite
        CursorColor = clGray
        IconGlyph = #61666
        IconGlyphPressed = #61666
        DescriptionText = 'Grids'
        Pressed = False
        GroupIndex = 1
        IconColorNormal = clGray
        IconColorHover = clBlack
        IconColorPressed = clGray
        DescriptionColorNormal = clGray
        DescriptionColorHover = clBlack
        DescriptionColorPressed = clGray
        IconOffsetX = 1
        OnClick = CWSStoreButton9Click
      end
    end
    object CWSStoreButton8: TCWSStoreButton
      AlignWithMargins = True
      Left = 3
      Top = 580
      Width = 72
      Height = 57
      Align = alBottom
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clGray
      Font.Height = -9
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      IconFontName = 'Segoe MDL2 Assets'
      BckNormalColor = clBtnFace
      BckHoverColor = clSilver
      BckPressedColor = clWhite
      CursorColor = clGray
      IconGlyph = #59718
      IconGlyphPressed = #61799
      DescriptionText = 'Info'
      Pressed = False
      GroupIndex = 1
      IconColorNormal = clGray
      IconColorHover = clBlack
      IconColorPressed = clGray
      DescriptionColorNormal = clGray
      DescriptionColorHover = clBlack
      DescriptionColorPressed = clGray
      OnClick = CWSStoreButton8Click
    end
  end
  object pnlContent: TPanel
    Left = 78
    Top = 30
    Width = 1018
    Height = 640
    Align = alClient
    BevelOuter = bvNone
    Caption = 'Panel1'
    ParentBackground = False
    TabOrder = 2
    object shpContent: TEsShape
      Left = 0
      Top = 48
      Width = 1018
      Height = 592
      Align = alClient
      Brush.Color = 15329769
      Corners = [TopLeft]
      Shape = RoundRectangle
      Sides = [Top, Left]
      ExplicitLeft = 112
      ExplicitTop = 224
      ExplicitWidth = 64
      ExplicitHeight = 64
    end
    object pnlTitle: TPanel
      Left = 0
      Top = 0
      Width = 1018
      Height = 48
      Align = alTop
      BevelOuter = bvNone
      Color = clWhite
      ParentBackground = False
      TabOrder = 0
      DesignSize = (
        1018
        48)
      object lblTitle: TLabel
        AlignWithMargins = True
        Left = 20
        Top = 3
        Width = 60
        Height = 42
        Margins.Left = 20
        Align = alLeft
        Alignment = taCenter
        Caption = 'lblTitle'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Segoe UI'
        Font.Style = [fsBold]
        ParentFont = False
        Layout = tlCenter
        ExplicitHeight = 25
      end
      object btnTheme: TCWSButton
        Left = 973
        Top = 6
        Width = 35
        Height = 35
        Anchors = [akTop, akRight]
        Color = clBtnFace
        TabOrder = 0
        IconFontName = 'Segoe MDL2 Assets'
        IconFontSize = 14
        IconOffsetX = 3
        IconOffsetY = 1
        BckNormalColor = clWhite
        BckHoverColor = clWhitesmoke
        BckPressedColor = 14737632
        BorderColorNormal = 13750737
        BorderColorHover = 13092807
        BorderColorPressed = 11776947
        IconGlyph = #59142
        IconGlyphPressed = #59142
        Caption = ''
        IconColorNormal = 2368548
        IconColorHover = 2368548
        IconColorPressed = 2368548
        CaptionColorNormal = 2368548
        CaptionColorHover = 2368548
        CaptionColorPressed = 2368548
        IconSpacing = 0
        BckDisabledColor = 15790320
        BorderColorDisabled = 14737632
        CaptionColorDisabled = 12434877
        IconColorDisabled = 12434877
        OnClick = btnThemeClick
      end
    end
    object pnlContentForm: TPanel
      AlignWithMargins = True
      Left = 1
      Top = 57
      Width = 1017
      Height = 583
      Margins.Left = 1
      Margins.Top = 9
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alClient
      BevelOuter = bvNone
      Color = 15329769
      ParentBackground = False
      TabOrder = 1
    end
  end
  object CWSDimOverlay1: TCWSDimOverlay
    ShowActivityIndicator = True
    IndicatorStyle = cisSegmented
    IndicatorColor = clBlack
    IndicatorTrackColor = clWhite
    IndicatorSize = 64
    IndicatorSegmentCount = 8
    IndicatorGap = 2
    IndicatorSpeed = 400
    TextFont.Charset = DEFAULT_CHARSET
    TextFont.Color = clWhite
    TextFont.Height = -13
    TextFont.Name = 'Segoe UI'
    TextFont.Style = []
    Left = 127
    Top = 103
  end
  object CWSSystemMenu1: TCWSSystemMenu
    CaptionRestore = '&Restore'
    CaptionMove = '&Move'
    CaptionSize = '&Size'
    CaptionMinimize = 'Mi&nimize'
    CaptionMaximize = 'Ma&ximize'
    CaptionClose = '&Close'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ItemHeight = 32
    Left = 264
    Top = 104
  end
end
